### PR TITLE
Publish all sonar messages on a single topic

### LINKED ISSUE #3: Publish all sonars on one topic
They have the link in the message, you can do this. It makes adding sonar support significantly simpler, as you only have to setup one subscriber instead of a dynamic number of them.

### PR DESCRIPTION
**Pull request by jim-v**
Fixes #3

### CODE REVIEW

**Comment by waynegramlich** [comment]
Should the topic be `sonars` instead of `sonar`.  Also, Travis is complaining about something.  Am I supposed to do some sort of test?  If so, I don't really have a clue.

**Comment by rohbotics** [comment]
I'm pretty sure the travis on loki_base_node is pretty bogus. I'll look into it.

**Comment by jim-v** [comment]
@waynegramlich I changed the name of the topic to `/sonars` and made the corresponding change to sonar_statistics.py.  Can you take a look, please.

**Comment by jim-v** [comment]
I've tested it on a loki, so I'm just asking for approval for the changes.

**Comment by waynegramlich** [comment]
Looks good.  I approve.

**Comment by rohbotics** [comment]
@waynegramlich FYI Github has a PR review mechanism. You can approve/request changes through that.

https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/

**Pull request merged**
